### ISSUE TITLE
File compiling problem

### ISSUE THREAD

**Issue by yhchen1123** [emreg00/guild#2]
Hi Emre, my name is Yuhao Chen and I'm trying to use guild to predict disease-associated genes. I download GUILD using SBI mirror and compile the file with your instruction. But error was found during compiling:
make: *** [makefile: 100: graph/Graph.o] Error 1

I am not familiar with c++, so I hope you can provide me with valuable suggestions for repairing this error.

And my operating system is Windows10 with gcc version 11.3.0, GNU Make 4.3.

Thanks for your help!

Yuhao Chen

**Comment by emreg00** [comment]
Hi Yuhao,

Sorry to hear that you are having issues. It is hard to tell without having
the full error message you get but most likely there is some (version)
incompatibility among the required tools / BOOST library (
https://github.com/emreg00/guild#requirements). Can you check the version
of BOOST (BGL)? If there is a windows specific error, you can also give it
a try using Windows Subsytem for Linux (
https://docs.microsoft.com/en-us/windows/wsl/about) or Cygwin (
https://www.cygwin.com/).

Best wishes,

Emre

**Comment by yhchen1123** [comment]
Hi Emre， 

Thinks for your reply. I tried compiling guild in WSL but found errors as follow:

Netween.cpp:133:25: error: expected primary-expression before ‘>’ token
  133 |     unordered_set<Vertex>::iterator setIt, setItEnd;
      |                         ^
Netween.cpp:133:37: error: missing template arguments before ‘setIt’
  133 |     unordered_set<Vertex>::iterator setIt, setItEnd;
      |                                     ^~~~~
Netween.cpp:140:9: error: ‘setIt’ was not declared in this scope
  140 |     for(setIt = setIncluded.begin(), setItEnd = setIncluded.end(); setIt != setItEnd; ++setIt) {
      |         ^~~~~
Netween.cpp:140:38: error: ‘setItEnd’ was not declared in this scope
  140 |     for(setIt = setIncluded.begin(), setItEnd = setIncluded.end(); setIt != setItEnd; ++setIt) {
      |                                      ^~~~~~~~
Netween.cpp:143:6: error: ‘seedIt’ was not declared in this scope; did you mean ‘seed48’?
  143 |  for(seedIt = setSeed.begin(), seedItEnd = setSeed.end(); seedIt != seedItEnd; ++seedIt) {
      |      ^~~~~~
      |      seed48
Netween.cpp:143:32: error: ‘seedItEnd’ was not declared in this scope
  143 |  for(seedIt = setSeed.begin(), seedItEnd = setSeed.end(); seedIt != seedItEnd; ++seedIt) {
      |                                ^~~~~~~~~
make: *** [Makefile:73: Netween.o] Error 1

I'm not familiar with the details of guild. So can you give me some guidance to fix it?

Thanks for your help and time.

**Comment by emreg00** [comment]
Hi Yuhao,

Thanks for sharing the error log, it seems to be an issue with not having Boost Graph Library properly set up. Can you please make sure that the [boost graph library (BGL)](https://sourceforge.net/projects/boost/files/boost/1.62.0/) is properly unpacked inside the parent folder before compiling the code? You might need to run "make clean" once you have the BGL files and then run "make". 

Hope this helps,

Emre

**Comment by yhchen1123** [comment]
Hi Emre,

Following your advice, the script works!

Thanks for your help!
